name: DoctorApp
description: Ung dung noi bo BV Da Khoa Tinh Phu Tho

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  graphql_flutter: ^5.0.0
  shared_preferences: ^2.0.8
  firebase_messaging: ^10.0.8
  flutter_local_notifications: ^9.0.0
  path_provider: ^2.0.5
  flutter_html: ^2.1.5
  # open_appstore: ^1.0.2  #open url in appstore
  flutter_bloc: ^7.3.0
  webview_flutter: ^2.1.1
  device_info: ^2.0.2
  intl: ^0.17.0
  url_launcher: ^6.0.12
  image_picker: ^0.8.4+2
  hex: ^0.2.0
  #  qrscan: ^0.2.17
  #barcode_scan: ^1.0.0
  universal_platform: ^1.0.0+1
  charts_flutter: ^0.11.0
  flutter_widget_from_html: ^0.7.0
  photo_view: ^0.13.0
  flutter_launcher_icons: ^0.9.2
  pie_chart: ^5.0.1
  package_info: ^2.0.2
  flutter_plugin_android_lifecycle: ^2.0.3
  flutter_dotenv: ^5.0.2
  date_time_picker: ^2.1.0
  flutter_svg: ^0.22.0
  signalr_core: ^1.1.1
  cached_network_image: ^3.2.0
  provider: ^6.0.2
  google_fonts: ^2.2.0
  #qr_code_scanner: ^0.3.5
  search_choices: ^2.0.20
  get: ^4.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "E:\\GitProject\\PSHaiPhong\\pshp_noibo\\icon_app.png"
#  image_path: "/Volumes/DATA/THONGMV/Project/PSHN/PSHN/ung_dung_noi_bo_benhvien/icon_app.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/icons/
    - assets/images/
    - assets/avatar/
    - assets/add_more.png
    - assets/avata_user.png
    - assets/back_icon_gray.png
    - assets/back_icon_white.png
    - assets/btmn_canhan_active.png
    - assets/btmn_canhan_gray.png
    - assets/btmn_dsbenhnhan_active.png
    - assets/btmn_dsbenhnhan_gray.png
    - assets/btmn_thongbao_gray.png
    - assets/btmn_thongbao_active.png
    - assets/cd_checkin_32.png
    - assets/cd_dattaikham_32.png
    - assets/cd_donthuoc_32.png
    - assets/cd_ketquakham_32.png
    - assets/cd_khambenh_32.png
    - assets/cd_thuthuat_32.png
    - assets/chidinh_32.png
    - assets/chidinh_black.png
    - assets/close_popup.png
    - assets/dangky_thanhcong_90.png
    - assets/datkham_khong_thanhcong_90.png
    - assets/edit_info_32.png
    - assets/gender_16.png
    - assets/icon_drop_down.png
    - assets/icon_home_active.png
    - assets/icon_huongdan_32.png
    - assets/icon_logout.png
    - assets/icon_next_function.png
    - assets/icon_notify_white.png
    - assets/icon_pass.png
    - assets/icon_phone_number.png
    - assets/icon_select_date.png
    - assets/icon_thongbao_32.png
    - assets/icon_thongtincanhan_32.png
    - assets/location_16.png
    - assets/logo.png
    - assets/phone_16.png
    - assets/qldatkham_48.png
    - assets/qldonthuoc_48.png
    - assets/qlkhambenh_48.png
    - assets/qltaikham_48.png
    - assets/qlthanhtoan_48.png
    - assets/qlxetnghiem_48.png
    - assets/qrcode_16.png
    - assets/scan_qr.png
    - assets/search_32.png
    - assets/sitemenu_changepass.png
    - assets/sitemenu_dsbenhnhan.png
    - assets/sitemenu_home.png
    - assets/sitemenu_icon_white.png
    - assets/sitemenu_thongke.png
    - assets/take_photo_32.png
    - assets/tintuc_48.png
    - assets/tuoithai_48.png
    - assets/defaultimage.png
    - assets/ic_clock.png
    - assets/ic_doctor.png
    - assets/img_delete.png
    - assets/img_add.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 400
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
